### ISSUE TITLE
Some confusion about type inference for constant words

### ISSUE THREAD

**Issue by apoelstra** [BlockstreamResearch/simplicity#142]
I have a couple questions about type inference for const words.

1. I believe the doccomment on `typeInference` should be updated: https://github.com/BlockstreamResearch/simplicity/blob/7be9a8725135ea81f6454968af574a6ca2390407/C/typeInference.c#L244-L245 Currently it says as a precondition that if a node is a `JET` then the `bound_var` variable must be correctly initialized; since adding `WORD`, the precondition should also be required if the node is `WORD`.

2. Why does `UNIT` leave its source type unbound while `WORD` fixes the source to be unit? It seems like `UNIT` could be thought of as a trivial form of `WORD` but this is a conspicuous difference. (I guess that unit is supposed to serve a "read and throw away an arbitrary input" role?)

**Comment by roconnor-blockstream** [comment]
Regarding 2, all jets are monomorphic, so if we want WORDs to be instances of a jets rather than their own special thing, we must to specify the input type.

**Comment by apoelstra** [comment]
A third question:

Const words are parsed as a numeric "depth" between 1 and 32 inclusive, from which we subtract 1 and index into the list of "initial types" currently given by https://github.com/BlockstreamResearch/simplicity/blob/7be9a8725135ea81f6454968af574a6ca2390407/C/primitive/elements/primitiveInitTy.inc

This file is documented as "all the types that might be used by jets" which sounds ad-hoc but conveniently all the initial ones are just powers of 2, in order. **However** the first **33** are powers of 2, while the code restricts us to using only the first **32**. Was this a deliberate restriction?

**Comment by apoelstra** [comment]
Ah, perfect, that makes sense.
