### ISSUE TITLE
Assertion failure in `decodeWitnessData`

### ISSUE THREAD

**Issue by apoelstra** [BlockstreamResearch/simplicity#151]
`decodeWitnessData` calls `readBitstring`, which has an assertion on the length to read. But the length to read is an unchecked value read from the serialized program. So you can trigger an assertion.

`761f001a00`, whatever that is, seems to trigger this.

Found by fuzzer.

**Comment by roconnor-blockstream** [comment]
https://github.com/BlockstreamResearch/simplicity/blob/8dbb735a1bc5b4ee8694c3ce23ff3f615657a597/C/bitstream.c#L217 is the assert that is failing?

**Comment by apoelstra** [comment]
Yes.

**Comment by apoelstra** [comment]
Also on deserialize.c:73 this can be triggered -- we try to parse values for constant word jets up to `1 << 31` or `0x80000000`, but the assert is set at `0x8000`.

**Comment by roconnor-blockstream** [comment]
Oh I see.  I think I mean to set the assertion to `0x80000000` and mistyped it.

**Comment by roconnor-blockstream** [comment]
`n <= 2^31` is the precondition that I am trying to check.  I cannot count.

**Comment by apoelstra** [comment]
Lol, me neither. Based on the `static_assert` above which says "check that size_t is at least 32 bits", I think so. I should've caught this during review.

**Comment by roconnor-blockstream** [comment]
What an irritating way to introduce a crashing bug.
