### ISSUE TITLE
A program which is just a hidden node shouldn't decode

### ISSUE THREAD

**Issue by apoelstra** [BlockstreamResearch/simplicity#155]
Example: `300000000000000000000000000000000000000000000000000000000000000000`

I would argue that a sole hidden node is a "hidden node outside of a CASE combinator" and should fail to decode with an `SIMPLICITY_ERR_HIDDEN`.

I can see both sides of this argument philosophically, but pragmatically, I'd also prefer that this doesn't decode, because in rust-simplicity we're planning to drop hidden nodes entirely, which means *we* won't be able to decode it, and I'd like to be able to fuzz that the C and Rust implementations decode exactly the same set of programs. (Well, except that the Rust code will decode fail nodes.)

**Comment by uncomputable** [comment]
I think the tech report should be updated to disallow hidden root nodes. Hidden nodes only make sense as children of case nodes. A hidden node as root is almost like an empty program, which is also disallowed.
