### ISSUE TITLE
Update sample transaction to work on testnet

### ISSUE THREAD

**Issue by asoltys** [BlockstreamResearch/simplicity#157]
The sample transaction featured in [this asciinema demo](https://asciinema.org/a/427264) no longer works. I [attempted](https://github.com/asoltys/elements/commit/6678b8ba99a3f7175bc0425b53f9ae45055f052b) a testnet construction but ran into issues:

`el testmempoolaccept '["020000000101a479028ae98ea68eeccd7363dedf22e3636bdbcdd0d298b48d2f58c1ba2728b20100000000feffffff0201647978f069666525c44cbb0881df748db03e5ad6efc07caa941af267bbf1d38c0100000000000182b800160014cddb7dc370b931651b8331469edeb0c5a56b9ae501647978f069666525c44cbb0881df748db03e5ad6efc07caa941af267bbf1d38c0100000000000003e8000000000000000003fdbe03e8e44902040810204174081680aea128a85a82d416fd0268167c00502d7c085b350a05805a340b4ee140b8170217020a85985c002e121706e022e001708e1027108a85c37830b8105c238985a02a164171570c1311703e0c2816dda2e2fe2613880542c42d41703e002e34e02281708e201704e21140b00b8b3860b89b88c502e1fc582e28e37140b00b405c002e260b8db9082e1e171af108b8d790028160171c7128b89b8d8502e2de430b8838d8502c02d0172139002e3ee25140b90fc8e1723790e281601724b9242e4471d0a05c73c8e171a7220502c02d017000b8ff91a2e51f214502e4a72705c95e488a05805c80e488b90fca3140b929c9a1729391e281601680b923ca01723f924281728f94a2e43f29c502c02e5072c44e002e4af2445c8de5a0a05805985bc2e1e45213986490204170130102c08141c2cf316616a0991c1c862481020b80b00b00b01b810a03ac830d0c30c30e1663e930fa45061861c2d23e930fc04507d42830f9987e0e283f00140b3187d461f5187e20141f848a05985a870b8585c1b821c2e0038e164071a01c9253139da418830c30c385992408105c04c04c05804de70b4e42c82d213821c1c80e023f0830fc245061f130fc34502c461f4187d061f890502c42d0494482814828148281482817080b858e1707245d021d020081602602040810204082ec1690a6a140b5058e22c426d16016d0b685b42da17061470b8ac70b900305c59c5a2e2b0b8a8272685c55c542059642e2f0b8d78d45c68138c85805a02d0171889c7a2816e181e08072c02e59930102280609e0c8830542c883854618830e30db4e38c3f38071c61b9c430e1603f31e61c2c02da17021b859c70b00b859071c70b1038c42e855e8711742c742e8a05d0b1d0b02e86fe855140b00ba1eba14c5d0bfd104281743af43d8ba183a188502c02d01743374388ba22ba184502e876e8741742b0542e881e8791742905d0d1d1042705150b20b685d111d0ec2e877e86e140ba1c3a1c05d09a150ba1cfa1b85d10fd116281743d743889d0b22a16617445f44a0ba11c2e887e8931744874408a05805d12fd1302e83d0ba257a1f45d137d13c2816016616e0b862ddc140b06a0205c7e3f214c3f417a0c305800d42cc7e8363f41b9b40a00e001c40cc0e021f42485d09603830ba2fba3344e8cd13a3344e8cd13a3344e6f85d1a7d15c274698ba34c2e8d30ba34c2e7102cc2dc038945d1327146c408f48000000000000000000000000ede33958fe2683b65053d6a8a2b4365b59e57e718f77da08a60f859d9d8b6884ceec558bca94d8151bf70cc7f2af492e4514dc391c020896b16e4692350cb43c4807c8f9f63637f70f84a17b678ca9467109ff1e50f6121bf00000000000000000000003b78ce563f89a0ed9414f5aa28ad0d96d6795f9c630000000000"]'
[
  {
    "txid": "f00d8a0e17caf4563298355edcdbc103af76e55ef7a8e915923fa1a57d2c5ef5",
    "wtxid": "8a21003314494332f817666472061c7547ffbe4eddd2ae44d2b65fd8d40869a8",
    "allowed": false,
    "reject-reason": "non-mandatory-script-verify-flag (Program has FAIL node)"
  }
]`

IRC discussion:

> 10:30 < uncomputable> asoltys: rust-simplicity from 2 weeks ago cannot parse your program. It says there is a type error
> 10:30 < uncomputable> I used hal-simplicity https://github.com/uncomputable/hal-simplicity to analyze your transaction
> 10:30 < uncomputable> I will update the code today so it compiles with the latest rust-simplicity code
> 10:50 < uncomputable> Updated, but the jet encoding seems to have changed since the testnet was launched :/
> 13:17 < roconnor> asoltys: In particular Simplicity.Elements.Programs.CheckSigHashAll.Lib was removed in 
>                   https://github.com/BlockstreamResearch/simplicity/pull/97, so that Haskell module won't even run anymore.
> 13:20 < roconnor> You will want to replace it with Simplicity.Elements.Programs.SigHash.Lib and replace hashAll with sigAllHash.

**Comment by roconnor-blockstream** [comment]
Fixed in <https://asciinema.org/a/598240>.
