### ISSUE TITLE
Incorrect weight calculations for Witness and Disconnect

### ISSUE THREAD

**Issue by roconnor-blockstream** [BlockstreamResearch/simplicity#159]
@uncomputable noticed the Haskell implementation of the weight cost of terms for Witnesses appears incorrect.

https://github.com/BlockstreamResearch/simplicity/blob/e5f74ca15ed553b769f3862d68b72271d1a98bd0/Haskell/Core/Simplicity/BitMachine/StaticAnalysis/Cost.hs#L40

It should have overhead and use `milli`.

**Comment by uncomputable** [comment]
Witness is also missing the overhead, which is present in the C code.

**Comment by roconnor-blockstream** [comment]
@uncomputable also noted on IRC that the disconnect combinator formula should be:

    overhead + 2 * bitSize(2^256 * A) + bitSize(B * C) + bitSize(B) + cost(s) + cost(t)

And the current implementation, both C and Haskell, is missing the `bitSize(B)` term.

**Comment by roconnor-blockstream** [comment]
https://github.com/BlockstreamResearch/simplicity/blob/e5f74ca15ed553b769f3862d68b72271d1a98bd0/Haskell/Core/Simplicity/BitMachine/StaticAnalysis/Cost.hs#L43

In fact, this implementation in Haskell isn't even close to being correct.  The use of `reifyProxy` is pulling in completely incorrect types.  Unfortunately the type manipulations being done here are fairly opaque and a bit hard to make clear.
