### ISSUE TITLE
Jet costs as part of Haskell library

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/simplicity#160]
The cost of a jet should be part of the Haskell library, [as said in this todo](https://github.com/BlockstreamResearch/simplicity/blob/e5f74ca15ed553b769f3862d68b72271d1a98bd0/Haskell-Generate/GenPrimitive.hs#L175). This would make code generation for Rust much easier and lead to less code duplication.

**Comment by uncomputable** [comment]
It would also be good to have a method that converts `Weight` to milli weight units (aka `Integer`). At least I had trouble replicating what `GenPrimitive.hs` does. Maybe there is an easy way that I don't know about.

**Comment by uncomputable** [comment]
#163 makes the benchmarks available as a module inside the Haskell generator code. I think that is good enough for now and we can close this issue.

**Comment by roconnor-blockstream** [comment]
I'm going to reopen this because I still need to pull the jet cost properly into the main Haskell code.
