### ISSUE TITLE
Crash on `cabal exec GenRustJets`

### ISSUE THREAD

**Issue by sanket1729** [BlockstreamResearch/simplicity#175]
```
sanket1729:~/simplicity$ cabal exec GenRustJets

GenRustJets: Simplicity.Bitcoin.Jets.jetCost: :TODO: Implement jets for Bitcoin and benchmark them.
CallStack (from HasCallStack):
  error, called at Haskell/Simplicity/Bitcoin/Jets.hs:346:29 in Simplicity-0.0.0-inplace:Simplicity.Bitcoin.Jets
```
Tested on commit: a3b6a63849ea3eb9db958c757759cc782223ca35, the tip of master

**Comment by roconnor-blockstream** [comment]
Fails in https://github.com/BlockstreamResearch/simplicity/pull/171 due to the fact we can no longer computer CMRs for bitcoin jets as jets now require having a known weight.

**Comment by roconnor-blockstream** [comment]
Fixed in https://github.com/BlockstreamResearch/simplicity/pull/176.
