### ISSUE TITLE
Disassembler and bounds-checker for C

### ISSUE THREAD

**Issue by apoelstra** [BlockstreamResearch/simplicity#20]
Would be useful for analytics and fuzzing to write some standalone tools for the C implementation. I can take this on.

**Comment by roconnor-blockstream** [comment]
A Haskell program for pretty-printing Simplicity expressions can be found at https://lists.ozlabs.org/pipermail/simplicity/2019/000023.html.

**Comment by roconnor-blockstream** [comment]
I think we have a disassembler now.  I'm not 100% what you meant by bounds-checker.

**Comment by apoelstra** [comment]
I think I meant the cost stuff exposed in #166.

As for a disassembler, agreed, we've done this on the Rust side. We haven't merged it yet but we've been using various incarnations of it for several weeks and don't need this issue anymore.

**Comment by roconnor-blockstream** [comment]
https://github.com/BlockstreamResearch/rust-simplicity for posterity.
