### ISSUE TITLE
Not WASM compatible

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/simplicity#206]
The current C code cannot be compiled for WASM, which prevents Simplicity to be run in the browser. rust-simplicity depends on C FFI, so it has the same problem. For comparison, libsecp can be compiled.

We have to remove incompatible standard library headers. So far it looks like these headers cause problems:

- stdio.h
- assert.h

**Comment by uncomputable** [comment]
I was able to replace stdio.h with stddef.h in #207. Assertions are still a problem. Maybe we can [define our own assertions like libsecp](https://github.com/bitcoin-core/secp256k1/pull/54). We still have to tell the compiler that certain paths are unreachable, or it will fire errors.

**Comment by apoelstra** [comment]
Standard assertions don't cause paths to be unreachable. It should be fine to replace C assertions with our own.

The bigger issue will be eliminating calls to `malloc` which is far easier in libsecp than in simplicity.

**Comment by apoelstra** [comment]
Great observation @roconnor-blockstream. Depending how stupid our compiler is, we may need to do some preprocessor hacking to just cut out all the non-jet C code. (I think right now we build the entire `C/` tree of the simplicity lib.)

**Comment by roconnor-blockstream** [comment]
I intended to have the C Makefile produce a static library for the jets, but I didn't have any actual consumers for such an artefact so I haven't bothered implementing it.

**Comment by uncomputable** [comment]
I added a separate jet target to the Makefile: #215

**Comment by uncomputable** [comment]
Fixed by #222
