### ISSUE TITLE
SHA jet fails

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/simplicity#221]
The following program fails at `jet_sha_256_ctx_8_add_32`. This is strange because SHA jets almost never fail, and the program type-checks.

```
sha256_init : 2^256 -> _
sha256_init := comp unit jet_sha_256_ctx_8_init

sha256 : 2^256 -> 2^256
sha256 := comp
    comp
        pair sha256_init iden
        jet_sha_256_ctx_8_add_32
    jet_sha_256_ctx_8_finalize

preimage := const 0x9dd01b56b15645143ead158dec19f8cea90bd0a9b2f81d21ffa3a4c64481d41c
image := const 0x0bcfe0e54e6cc7d34f4f7c1df0b0f503f2f712912a0605b414ed337f7f032e03

main := comp
    comp
        pair (comp preimage sha256) image
        jet_eq_256
    jet_verify
```

The program is taken from [our post on sharing and disconnect](https://blog.blockstream.com/simplicity-sharing-of-witness-and-disconnect/) (_Consider the following program, which checks whether the user has found a SHA256 "fixed point")_

The (pre)images are taken from a [test vector from bitcoin-hashes](https://github.com/rust-bitcoin/rust-bitcoin/blob/53461f71c9cd6ed49acff61396758f53f8fa3de8/hashes/src/sha256.rs#L905).

**Comment by roconnor-blockstream** [comment]
You are missing

https://github.com/rust-bitcoin/rust-bitcoin/blob/53461f71c9cd6ed49acff61396758f53f8fa3de8/hashes/src/sha256.rs#L899-L900

from your program

**Comment by uncomputable** [comment]
@roconnor-blockstream Thanks for pointing this out. Updating the (pre)images fixes the program in rust-simplicity.

```
preimage := const 0x0000000000000000000000000000000000000000000000000000000000000000
image := const 0x66687aadf862bd776c8fc18b8e9f8e20089714856ee233b3902a591d0d5f2925
```

The webide (where this error originated) still returns an error, but this has likely to do with WASM or with the IDE itself.
