### ISSUE TITLE
C: clamping of `budget` in `elements_simplicity_execSimplicity` is incorrect

### ISSUE THREAD

**Issue by apoelstra** [BlockstreamResearch/simplicity#234]
In `elements_simplicity_execSimplicity` we clamp the passed `budget` value to ensure it does not exceed `BUDGET_MAX`. But we do not check for negative values. If you pass a negative value, it will be casted to a `ubounded` that exceeds `BUDGET_MAX`, eventually triggering an assertion failure in eval.c.

There are three ways we might handle negative values:
* clamping to 0
* returning an error
* asserting in execSimplicity

I have no preference about which.

**Comment by roconnor-blockstream** [comment]
I'm leaning towards making the budget non-negative a precondition and adding an assertion in execSimplicity.

**Comment by roconnor-blockstream** [comment]
Fixed in 'staging'.
