### ISSUE TITLE
The changes required to match Coq's Hashblock CMR with Haskell's exceed the scope of this PR. Let's merge this PR for now with a working intermediate CMR. I will look into updating Coq's shifting and rotation logic.

### ISSUE THREAD

**Issue by roconnor-blockstream** [BlockstreamResearch/simplicity#261]
The changes required to match Coq's Hashblock CMR with Haskell's exceed the scope of this PR. Let's merge this PR for now with a working intermediate CMR. I will look into updating Coq's shifting and rotation logic.

_Originally posted by @uncomputable in https://github.com/BlockstreamResearch/simplicity/issues/112#issuecomment-1385039199_

**Comment by uncomputable** [comment]
This is an issue from a long time ago, but it is still relevant: The SHA256 hashblock logic that we proved correct in Coq no longer matches the Haskell implementation of the hashblock jet. We need to update the Coq hashblock implementation and rewrite the proofs.

I never actually got around to doing this ^^
