### ISSUE TITLE
Quickcheck Infrastructure: Haskell <> C (Jet)

### ISSUE THREAD

**Issue by ProofOfKeags** [BlockstreamResearch/simplicity#32]
I'm cutting this issue mostly for myself since this is something I've been working on and off for a bit. However, due to the nature of the Bitcoin Core Slack channel where I had discussed this before, my chat history with @roconnor-blockstream has been erased. I am moving discussion here for permanence.

The place I had left off was trying to get the FFI infrastructure in the Haskell project set up so that we can compare the simplicity programs written in Haskell with their corresponding Jets. Quickcheck style property testing offers a very nice place on the power-weight continuum to be able to check that the Haskell and C implementations of things match. As such, I'd like to get some of that infrastructure into the project.

The snag I had run into was that `frameItem` in the C project is defined to use a `UWORD*` which is defined in-project to use a `uint_fast16_t`. On my system (MacOS 10.15), the "fast" versions all match their standard counterparts (uint_fast16_t ~ uint16_t), but due to the nature of the typedef, I'm reasonably sure that cannot hold in general. As such, I am currently trying to figure out if I can get the FFI module to be aware of the `stdint.h` file that is on people's systems. If this is the case we can successfully abstract over the `UWORD*`, and marshalling inputs across the FFI boundary will "take care of itself".

@roconnor-blockstream Last time we spoke about this I remember you had an alternative idea for this, but unfortunately I don't remember what it was. If you remember your previous thoughts, have new ones, or have a better overall approach, I'd appreciate advice here, but absent that I'm going to proceed as I have outlined above.

**Comment by roconnor-blockstream** [comment]
I have some fresh thoughts on this.  I remember I designed `UWORD` so it can be easily overridden using a compile time gcc flag, e.g. `-D'UWORD=unsigned int'`.  Feel free to start with that if it helps you get started.

That said, I think you ought to be able to use the frame function in `frame.h` to marshal values into and out of the frame in a way independent of the `UWORD` size.  At the very least you can use the slow bitwise interface to the frames.

**Comment by roconnor-blockstream** [comment]
We now have an experimental branch with FFI bindings for C jets @ https://github.com/ElementsProject/simplicity/pull/37

The bindings work by calling into the bitwise interface to frames in C to manipulate frames.  Some stub functions specific to the Haskell FFI were needed because GHC's FFI cannot bind C functions that pass `struct`s by value.  At the same time we add constants, such as `sizeof(UWORD)` to C file with stub functions, which provides all we need to know about `UWORD` in practice.

**Comment by roconnor-blockstream** [comment]
Completed in https://github.com/BlockstreamResearch/simplicity/pull/34.
