### ISSUE TITLE
Remove obsolete secp256k1git / mysecp256k1 / Simplicity.Libsecp256k1.FFI

### ISSUE THREAD

**Issue by np** [BlockstreamResearch/simplicity#64]
Where is this repo published ?

**Comment by roconnor-blockstream** [comment]
Are you looking for https://github.com/ElementsProject/simplicity/pull/34 or for https://github.com/ElementsProject/simplicity/blob/master/Haskell/Core/Simplicity/Programs/LibSecp256k1.hs?

**Comment by np** [comment]
Nope, I'm referring to the secp256k1git parameter of the mylibsecp256k1.nix derivation.

**Comment by roconnor-blockstream** [comment]
These things are remnants of obsolete code and they are not used in the build process.  I will remove them.

The old functionality will be replaced by the code in PR #34.

**Comment by np** [comment]
Thanks

**Comment by roconnor-blockstream** [comment]
Fixed in #138.
